//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlsBox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlsBox.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Devices.
        /// </summary>
        public static string Find_Devices {
            get {
                return ResourceManager.GetString("Find_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1.
        /// </summary>
        public static string Item_1 {
            get {
                return ResourceManager.GetString("Item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 10.
        /// </summary>
        public static string Item_10 {
            get {
                return ResourceManager.GetString("Item_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 11.
        /// </summary>
        public static string Item_11 {
            get {
                return ResourceManager.GetString("Item_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 12.
        /// </summary>
        public static string Item_12 {
            get {
                return ResourceManager.GetString("Item_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 13.
        /// </summary>
        public static string Item_13 {
            get {
                return ResourceManager.GetString("Item_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 14.
        /// </summary>
        public static string Item_14 {
            get {
                return ResourceManager.GetString("Item_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 15.
        /// </summary>
        public static string Item_15 {
            get {
                return ResourceManager.GetString("Item_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 16.
        /// </summary>
        public static string Item_16 {
            get {
                return ResourceManager.GetString("Item_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 17.
        /// </summary>
        public static string Item_17 {
            get {
                return ResourceManager.GetString("Item_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 18.
        /// </summary>
        public static string Item_18 {
            get {
                return ResourceManager.GetString("Item_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 19.
        /// </summary>
        public static string Item_19 {
            get {
                return ResourceManager.GetString("Item_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2.
        /// </summary>
        public static string Item_2 {
            get {
                return ResourceManager.GetString("Item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 20.
        /// </summary>
        public static string Item_20 {
            get {
                return ResourceManager.GetString("Item_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 3.
        /// </summary>
        public static string Item_3 {
            get {
                return ResourceManager.GetString("Item_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 4.
        /// </summary>
        public static string Item_4 {
            get {
                return ResourceManager.GetString("Item_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 5.
        /// </summary>
        public static string Item_5 {
            get {
                return ResourceManager.GetString("Item_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 6.
        /// </summary>
        public static string Item_6 {
            get {
                return ResourceManager.GetString("Item_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 7.
        /// </summary>
        public static string Item_7 {
            get {
                return ResourceManager.GetString("Item_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 8.
        /// </summary>
        public static string Item_8 {
            get {
                return ResourceManager.GetString("Item_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 9.
        /// </summary>
        public static string Item_9 {
            get {
                return ResourceManager.GetString("Item_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Item.
        /// </summary>
        public static string LargeItem {
            get {
                return ResourceManager.GetString("LargeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum default size is 20% of the size of the parent ScatterView.
        /// </summary>
        public static string MaximumDefaultSize {
            get {
                return ResourceManager.GetString("MaximumDefaultSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place tag 0xC0 here.
        /// </summary>
        public static string PlaceTagHere {
            get {
                return ResourceManager.GetString("PlaceTagHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        public static string Recycle_Bin {
            get {
                return ResourceManager.GetString("Recycle_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeye Correction.
        /// </summary>
        public static string Redeye_Correction {
            get {
                return ResourceManager.GetString("Redeye_Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Text Input Controls.
        /// </summary>
        public static string TextInputControls {
            get {
                return ResourceManager.GetString("TextInputControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
