// Supress FxCop messages for violations that occur in generated code
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "DataVisualizer.Window1.#OnWindowUnavailable(object, EventArgs)", Justification = "Used by XAML")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "DataVisualizer.Window1.#OnWindowNoninteractive(object, EventArgs)", Justification="Used by XAML")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "DataVisualizer.Window1.#OnWindowInteractive(object, EventArgs)", Justification = "Used by XAML")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Visualizer", Justification = "Visualizer is correctly spelled")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Visualizer", Scope = "type", Target = "DataVisualizer.TouchDataVisualizer", Justification = "Visualizer is correctly spelled")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Visualizer", Scope = "namespace", Target = "DataVisualizer", Justification = "Visualizer is correctly spelled")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "DataVisualizer.TouchDiagram.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)", Justification="Casting caused by XAML")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "DataVisualizer.TouchDataVisualizer.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)", Justification = "Casting caused by XAML")]
